profiles and rtx config

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,9 +17,16 @@ jobs:
       uses: DeterminateSystems/nix-installer-action@main
     - name: Setup nix-darwin
       run: |
-        echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
-        /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t &>/dev/null || true
-    - name: Build and switch to nix-darwin env
-      run: |
-        nix build .#darwinConfigurations.github-ci.system
-        ./result/sw/bin/darwin-rebuild switch --flake .#github-ci
+        if ! grep -q '^run\b' /etc/synthetic.conf 2>/dev/null; then
+          echo "setting up /run via /etc/synthetic.conf..."
+          echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
+          /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -B &>/dev/null || true
+          /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t &>/dev/null || true
+          if ! test -L /run; then
+            echo "warning: apfs.util failed to symlink /run"
+          fi
+        fi
+    - name: Build nix-darwin ci env
+      run: nix build .#darwinConfigurations.ci.system
+    - name: Switch to nix-darwin ci env
+      run: ./result/sw/bin/darwin-rebuild switch --flake .#ci
