more cases for mounting /run

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,6 +17,7 @@ jobs:
       uses: DeterminateSystems/nix-installer-action@main
     - name: Setup nix-darwin
       run: |
+        # From https://github.com/LnL7/nix-darwin/blob/master/pkgs/darwin-installer/installer.nix#L40-L56
         if ! grep -q '^run\b' /etc/synthetic.conf 2>/dev/null; then
           echo "setting up /run via /etc/synthetic.conf..."
           echo -e "run\tprivate/var/run" | sudo tee -a /etc/synthetic.conf >/dev/null
@@ -25,6 +26,13 @@ jobs:
           if ! test -L /run; then
             echo "warning: apfs.util failed to symlink /run"
           fi
+        fi
+        if ! test -L /run; then
+            echo "setting up /run..."
+            sudo ln -sfn private/var/run /run
+        fi
+        if ! test -L /run; then
+          echo "warning: failed to symlink /run"
         fi
     - name: Build nix-darwin ci env
       run: nix build .#darwinConfigurations.ci.system
